[pytest]
pythonpath =
    .
    tests
    app/data_layer/sources/bhuvan_nrsc
    app/data_layer/sources/cwc_nwic
    app/data_layer/sources/gsi_bhusanket
    app/data_layer/sources/historical
    app/data_layer/sources/imd
    app/data_layer/sources/lgd
    app/data_layer/sources/mosdac
    app/data_layer/sources/ndem
    app/data_layer/sources/smap
testpaths =
    tests
    app/data_layer/sources
