"""
Predefined, verified disaster safety instruction templates (SIH 26192).

In strict accordance with emergency protocol standards:
- Critical emergency safety directives are NEVER generated by unconstrained AI.
- Predefined, reviewed message templates are used for all safety text.
- Dynamic fields (village, risk level, risk window, shelter, distance, capacity)
  are cleanly injected into structured slots.
- Multi-language support: English (en), Hindi (hi), Tamil (ta).
"""
from __future__ import annotations
from typing import Dict, Any


SUPPORTED_LANGUAGES = ("en", "hi", "ta")


HAZARD_NAMES = {
    "en": {
        "flood": "FLASH FLOOD",
        "landslide": "LANDSLIDE",
        "combined": "FLASH FLOOD & LANDSLIDE",
    },
    "hi": {
        "flood": "अचानक बाढ़",
        "landslide": "भूस्खलन",
        "combined": "बाढ़ व भूस्खलन",
    },
    "ta": {
        "flood": "திடீர் வெள்ளம்",
        "landslide": "நிலச்சரிவு",
        "combined": "திடீர் வெள்ளம் & நிலச்சரிவு",
    },
}


TEMPLATES: Dict[str, Dict[str, Dict[str, str]]] = {
    "en": {
        "CRITICAL": {
            "header": "🚨 {hazard} ALERT — {village}",
            "risk_line": "Risk Level: CRITICAL ({prob}% probability)",
            "window_line": "Estimated Risk Window: {window}",
            "summary": "Heavy rainfall and rapid hazard escalation detected.",
            "action": (
                "ACTION:\n"
                "Move immediately to the nearest VERIFIED designated evacuation shelter "
                "or safe higher-ground location as instructed by local authorities."
            ),
            "do_not": (
                "DO NOT:\n"
                "- enter or cross flooded roads, bridges or flowing water\n"
                "- drive through floodwater\n"
                "- remain in low-lying flood-prone areas"
            ),
            "priority": "Prioritize children, elderly people and people requiring assistance.",
            "essentials": "Carry essential medicines, water, identification/documents and your phone if safe to do so.",
            "shelter_block": "Designated Shelter: {shelter_name} (Distance: {distance} km, Capacity: {capacity})",
            "footer": "Follow official local-authority evacuation instructions.",
        },
        "HIGH": {
            "header": "⚠️ {hazard} WARNING — {village}",
            "risk_line": "Risk Level: HIGH ({prob}% probability)",
            "window_line": "Estimated Risk Window: {window}",
            "summary": "High risk detected for {window}.",
            "action": (
                "PREPARE TO EVACUATE.\n"
                "Keep essential medicines, water, documents and phones ready.\n"
                "Move vulnerable family members to a safe location if instructed by authorities."
            ),
            "do_not": (
                "DO NOT:\n"
                "- walk or drive through flowing/flooded water\n"
                "- enter low-lying or unstable slope areas"
            ),
            "priority": "Stay in contact with local ward representatives and emergency response teams.",
            "essentials": "Keep emergency supplies, battery banks and emergency contact numbers ready.",
            "shelter_block": "Designated Shelter: {shelter_name} (Distance: {distance} km, Capacity: {capacity})",
            "footer": "Monitor official local-authority instructions.",
        },
        "MODERATE": {
            "header": "⚠️ {hazard} RISK NOTICE — {village}",
            "risk_line": "Risk Level: MODERATE ({prob}% probability)",
            "window_line": "Monitoring Window: {window}",
            "summary": "Increased hazard risk detected. Elevated ground saturation.",
            "action": (
                "Stay alert and monitor official updates.\n"
                "Keep emergency supplies ready.\n"
                "Avoid low-lying riverbanks and steep slope corridors."
            ),
            "do_not": "Do not enter flowing water or unstable slope cuts.",
            "priority": "Inform neighbors and check drainage around properties.",
            "essentials": "Keep mobile phones charged and monitor weather advisories.",
            "shelter_block": "Nearest Shelter: {shelter_name} (Distance: {distance} km)",
            "footer": "Decision support notice — monitor official District EOC updates.",
        },
        "LOW": {
            "header": "ℹ️ {hazard} ADVISORY — {village}",
            "risk_line": "Risk Level: LOW ({prob}% probability)",
            "window_line": "Monitoring Window: {window}",
            "summary": "Normal monitoring parameters. Risk currently within baseline thresholds.",
            "action": "Routine vigilance. No evacuation required.",
            "do_not": "Avoid unnecessary travel through active mountain gorges during downpours.",
            "priority": "Standard community preparedness.",
            "essentials": "Monitor local weather reports.",
            "shelter_block": "Designated Shelter on Standby: {shelter_name}",
            "footer": "FlashGuard Early Warning System — Routine Observation Mode.",
        },
    },
    "hi": {
        "CRITICAL": {
            "header": "🚨 {hazard} आपातकालीन चेतावनी — {village}",
            "risk_line": "जोखिम स्तर: गंभीर (CRITICAL - {prob}%)",
            "window_line": "अनुमानित जोखिम समय: {window}",
            "summary": "अत्यधिक वर्षा एवं तीव्र जलभराव/भूस्खलन का गंभीर संकट उत्पन्न हो गया है।",
            "action": (
                "जीवन-रक्षा कार्रवाई:\n"
                "स्थानीय प्रशासन के निर्देशानुसार तुरंत निकटतम सत्यापित आपदा आश्रय "
                "या सुरक्षित ऊंचे स्थान पर जाएं।"
            ),
            "do_not": (
                "क्या न करें:\n"
                "- जलमग्न सड़कों, रपटों, पुलों या बहते पानी में कतई न जाएं\n"
                "- बाढ़ के पानी में वाहन न चलाएं\n"
                "- नदी किनारे एवं निचले बाढ़-संभावित क्षेत्रों में न रहें"
            ),
            "priority": "बच्चों, वृद्धों एवं दिव्यांगजनों को सुरक्षित स्थान पर ले जाने में प्राथमिकता दें।",
            "essentials": "यदि सुरक्षित हो तो आवश्यक दवाएं, पीने का पानी, जरूरी दस्तावेज एवं मोबाइल फोन साथ रखें।",
            "shelter_block": "सत्यापित राहत आश्रय: {shelter_name} (दूरी: {distance} किमी, क्षमता: {capacity})",
            "footer": "जिला आपदा प्रबंधन प्राधिकरण एवं आधिकारिक स्थानीय निर्देशों का तत्काल पालन करें।",
        },
        "HIGH": {
            "header": "⚠️ {hazard} चेतावनी — {village}",
            "risk_line": "जोखिम स्तर: उच्च (HIGH - {prob}%)",
            "window_line": "अनुमानित जोखिम समय: {window}",
            "summary": "अगले {window} के लिए गंभीर जलभराव व भूस्खलन की चेतावनी।",
            "action": (
                "निकासी के लिए तैयार रहें:\n"
                "आवश्यक दवाएं, पीने का पानी, जरूरी दस्तावेज व मोबाइल चार्ज रखें।\n"
                "प्रशासन के निर्देशानुसार परिवार के संवेदनशील सदस्यों को सुरक्षित स्थान पर भेजें।"
            ),
            "do_not": (
                "क्या न करें:\n"
                "- बहते पानी या उफनती नालियों को पार करने का प्रयास न करें\n"
                "- ढलान वाले असुरक्षित रास्तों पर न जाएं"
            ),
            "priority": "ग्राम प्रधान एवं स्थानीय आपदा मित्रों के संपर्क में रहें।",
            "essentials": "टॉर्च, प्राथमिक चिकित्सा किट और आपातकालीन नंबर 1077/112 तैयार रखें।",
            "shelter_block": "नामित राहत आश्रय: {shelter_name} (दूरी: {distance} किमी, क्षमता: {capacity})",
            "footer": "स्थानीय प्रशासन एवं राज्य आपदा प्रबंधन के दिशा-निर्देशों का अनुसरण करें।",
        },
        "MODERATE": {
            "header": "⚠️ {hazard} जोखिम सूचना — {village}",
            "risk_line": "जोखिम स्तर: मध्यम (MODERATE - {prob}%)",
            "window_line": "निगरानी अवधि: {window}",
            "summary": "वर्षा एवं जलस्तर में वृद्धि दर्ज की गई है।",
            "action": (
                "सतर्क रहें और आधिकारिक मौसम बुलेटिन पर नजर रखें।\n"
                "आपातकालीन आवश्यक सामग्री तैयार रखें।\n"
                "निचले नदी-तटीय क्षेत्रों एवं तीखे ढलानों से दूर रहें।"
            ),
            "do_not": "बहते पानी या जलमग्न रास्तों में प्रवेश न करें।",
            "priority": "आस-पड़ोस के लोगों को सूचित करें और जल निकासी व्यवस्था सुचारू रखें।",
            "essentials": "फोन चार्ज रखें और सरकारी निर्देशों पर नजर बनाए रखें।",
            "shelter_block": "निकटतम सुरक्षित आश्रय: {shelter_name} (दूरी: {distance} किमी)",
            "footer": "निर्णय-समर्थन सूचना — जिला आपातकालीन परिचालन केंद्र (EOC) के निर्देशों पर ध्यान दें।",
        },
        "LOW": {
            "header": "ℹ️ {hazard} निगरानी सलाह — {village}",
            "risk_line": "जोखिम स्तर: सामान्य (LOW - {prob}%)",
            "window_line": "निगरानी अवधि: {window}",
            "summary": "वर्तमान में स्थिति सामान्य है। जोखिम निर्धारित सीमा के भीतर है।",
            "action": "सामान्य सतर्कता बरतें। किसी विशेष निकासी की आवश्यकता नहीं है।",
            "do_not": "तेज बारिश के दौरान पहाड़ी रास्तों पर अनावश्यक यात्रा से बचें।",
            "priority": "सामान्य सामुदायिक सजगता।",
            "essentials": "मौसम अपडेट पर सामान्य दृष्टि रखें।",
            "shelter_block": "नामित आपातकालीन आश्रय (स्टैंडबाय): {shelter_name}",
            "footer": "फ़्लैशगार्ड पूर्व-चेतावनी प्रणाली — नियमित निगरानी मोड।",
        },
    },
    "ta": {
        "CRITICAL": {
            "header": "🚨 {hazard} அவசர எச்சரிக்கை — {village}",
            "risk_line": "அபாய நிலை: மிக ஆபத்தானது (CRITICAL - {prob}%)",
            "window_line": "மதிப்பிடப்பட்ட கால அளவு: {window}",
            "summary": "கனமழை மற்றும் விரைவான வெள்ளப்பெருக்கு/நிலச்சரிவு அபாயம் கண்டறியப்பட்டுள்ளது.",
            "action": (
                "உடனடி பாதுகாப்பு நடவடிக்கை:\n"
                "உள்ளூர் அதிகாரிகளின் வழிகாட்டுதலின்படி, உடனடியாக அருகிலுள்ள "
                "சரிபார்க்கப்பட்ட நிவாரண முகாமிற்கு அல்லது பாதுகாப்பான மேடான பகுதிக்கு செல்லவும்."
            ),
            "do_not": (
                "செய்யக்கூடாதவை:\n"
                "- வெள்ளம் சூழ்ந்த சாலைகள், பாலங்கள் அல்லது ஓடும் நீரை கடக்க வேண்டாம்\n"
                "- வெள்ள நீரில் வாகனங்களை இயக்க வேண்டாம்\n"
                "- தாழ்வான நீர்நிலைப் பகுதிகளில் தங்கியிருக்க வேண்டாம்"
            ),
            "priority": "குழந்தைகள், முதியவர்கள் மற்றும் மாற்றுத்திறனாளிகளுக்கு முன்னுரிமை அளிக்கவும்.",
            "essentials": "அத்தியாவசிய மருந்துகள், குடிநீர், முக்கிய ஆவணங்கள் மற்றும் தொலைபேசியை எடுத்துச் செல்லவும்.",
            "shelter_block": "நியமிக்கப்பட்ட முகாம்: {shelter_name} (தொலைவு: {distance} கி.மீ, கொள்ளளவு: {capacity})",
            "footer": "அதிகாரப்பூர்வ பேரிடர் மீட்புக் குழுக்களின் (NDRF/SDMA) வழிமுறைகளை பின்பற்றவும்.",
        },
        "HIGH": {
            "header": "⚠️ {hazard} எச்சரிக்கை — {village}",
            "risk_line": "அபாய நிலை: அதிகம் (HIGH - {prob}%)",
            "window_line": "மதிப்பிடப்பட்ட கால அளவு: {window}",
            "summary": "அடுத்த {window} காலத்திற்கு தீவிர வெள்ள அபாயம் உள்ளது.",
            "action": (
                "வெளியேற தயாராக இருங்கள்:\n"
                "அத்தியாவசிய மருந்துகள், குடிநீர் மற்றும் ஆவணங்களை தயார் நிலையில் வைக்கவும்.\n"
                "அதிகாரிகளின் உத்தரவின்படி குடும்ப உறுப்பினர்களை பாதுகாப்பான இடங்களுக்கு மாற்றவும்."
            ),
            "do_not": (
                "செய்யக்கூடாதவை:\n"
                "- ஓடும் நீரில் நடக்கவோ வாகனங்களை இயக்கவோ வேண்டாம்\n"
                "- பலவீனமான மலைச்சரிவு பகுதிகளில் நிற்க வேண்டாம்"
            ),
            "priority": "உள்ளூர் பேரிடர் கண்காணிப்புக் குழுக்களுடன் தொடர்பில் இருங்கள்.",
            "essentials": "கைவிளக்கு மற்றும் அவசர உதவி எண்களை (1077/112) தயாராக வைக்கவும்.",
            "shelter_block": "நியமிக்கப்பட்ட முகாம்: {shelter_name} (தொலைவு: {distance} கி.மீ, கொள்ளளவு: {capacity})",
            "footer": "அரசு அதிகாரிகளின் அதிகாரப்பூர்வ அறிவிப்புகளை கண்காணிக்கவும்.",
        },
        "MODERATE": {
            "header": "⚠️ {hazard} அபாய அறிவிப்பு — {village}",
            "risk_line": "அபாய நிலை: நடுத்தரமானது (MODERATE - {prob}%)",
            "window_line": "கண்காணிப்பு காலம்: {window}",
            "summary": "மழைப்பொழிவு மற்றும் நீர்மட்டம் உயர்ந்துள்ளது. விழிப்புடன் இருக்கவும்.",
            "action": (
                "விழிப்புடன் இருந்து அதிகாரப்பூர்வ வானிலை அறிக்கைகளை கவனிக்கவும்.\n"
                "அவசர பொருட்களை தயார் நிலையில் வைக்கவும்.\n"
                "ஆற்றங்கரைகள் மற்றும் சரிவுப் பகுதிகளை தவிர்க்கவும்."
            ),
            "do_not": "ஓடும் நீரில் அல்லது நீரில் மூழ்கிய பாதைகளில் நுழைய வேண்டாம்.",
            "priority": "அண்டை வீட்டாருக்கு தகவல் தெரிவித்து பாதுகாப்பை உறுதி செய்யவும்.",
            "essentials": "தொலைபேசி மின்கலனை முழுமையாக வைத்திருக்கவும்.",
            "shelter_block": "அருகிலுள்ள முகாம்: {shelter_name} (தொலைவு: {distance} கி.மீ)",
            "footer": "முடிவெடுக்கும் ஆதரவு தகவல் — மாவட்ட அவசர கால கட்டுப்பாட்டு மையத்தை கவனிக்கவும்.",
        },
        "LOW": {
            "header": "ℹ️ {hazard} ஆலோசனை — {village}",
            "risk_line": "அபாய நிலை: குறைவு (LOW - {prob}%)",
            "window_line": "கண்காணிப்பு காலம்: {window}",
            "summary": "இயல்பான கண்காணிப்பு நிலை. அபாயம் எல்லைக்குள் உள்ளது.",
            "action": "வழக்கமான விழிப்புணர்வு போதுமானது. இடப்பெயர்வு தேவையில்லை.",
            "do_not": "கனமழையின் போது தேவையற்ற மலைப்பயணங்களை தவிர்க்கவும்.",
            "priority": "வழக்கமான சமூக பாதுகாப்பு.",
            "essentials": "வானிலை தகவல்களை தொடர்ந்து கவனிக்கவும்.",
            "shelter_block": "தயார் நிலையில் உள்ள முகாம்: {shelter_name}",
            "footer": "ஃபிளாஷ்கார்ட் ஆரம்ப எச்சரிக்கை கட்டமைப்பு — வழக்கமான நிலை.",
        },
    },
}


def render_alert_message(
    village: str,
    hazard: str,
    risk_level: str,
    probability: float,
    window: str,
    language: str = "en",
    shelter: Dict[str, Any] | None = None,
) -> str:
    """Render a verified, predefined safety alert message."""
    lang = language.lower() if language and language.lower() in SUPPORTED_LANGUAGES else "en"
    risk = risk_level.upper() if risk_level else "MODERATE"
    if risk not in ("CRITICAL", "HIGH", "MODERATE", "LOW"):
        risk = "MODERATE"

    haz_key = hazard.lower() if hazard in ("flood", "landslide", "combined") else "flood"
    hazard_str = HAZARD_NAMES.get(lang, HAZARD_NAMES["en"]).get(haz_key, "FLASH FLOOD")
    prob_int = int(round(probability * 100)) if probability <= 1.0 else int(probability)
    win_str = window or ("Next 2–3 hours" if lang == "en" else "अगले 2-3 घंटे" if lang == "hi" else "அடுத்த 2-3 மணி நேரம்")

    tpl_dict = TEMPLATES[lang][risk]

    shelter_str = ""
    if shelter and shelter.get("name"):
        s_name = shelter["name"]
        dist = shelter.get("distance_km", 1.5)
        cap = shelter.get("capacity", 500)
        shelter_str = tpl_dict["shelter_block"].format(
            shelter_name=s_name,
            distance=dist,
            capacity=cap,
        )
    else:
        if lang == "hi":
            shelter_str = "नामित आश्रय: कोई सत्यापित आश्रय उपलब्ध नहीं (सुरक्षित ऊंचे स्थान पर जाएं)"
        elif lang == "ta":
            shelter_str = "நியமிக்கப்பட்ட முகாம்: முகாம் எதுவும் இல்லை (பாதுகாப்பான மேடான பகுதிக்கு செல்லவும்)"
        else:
            shelter_str = "Designated Shelter: No verified shelter currently in system (Seek local safe higher ground)"

    header = tpl_dict["header"].format(hazard=hazard_str, village=village)
    risk_line = tpl_dict["risk_line"].format(prob=prob_int)
    window_line = tpl_dict["window_line"].format(window=win_str)
    summary = tpl_dict["summary"].format(window=win_str)
    action = tpl_dict["action"]
    do_not = tpl_dict["do_not"]
    priority = tpl_dict["priority"]
    essentials = tpl_dict["essentials"]
    footer = tpl_dict["footer"]

    lines = [
        header,
        "",
        risk_line,
        window_line,
        "",
        summary,
        "",
        action,
        "",
        do_not,
        "",
        priority,
        essentials,
        "",
        shelter_str,
        "",
        footer,
    ]

    return "\n".join(lines)


def render_short_sms(
    village: str,
    hazard: str,
    risk_level: str,
    window: str,
    shelter_name: str | None = None,
    language: str = "en",
) -> str:
    """Render concise 160-char SMS payload for mobile transmission."""
    lang = language.lower() if language and language.lower() in SUPPORTED_LANGUAGES else "en"
    risk = risk_level.upper() if risk_level else "MODERATE"
    haz_key = hazard.lower() if hazard in ("flood", "landslide", "combined") else "flood"
    hazard_str = HAZARD_NAMES.get(lang, HAZARD_NAMES["en"]).get(haz_key, "FLASH FLOOD")
    sh = shelter_name or ("Designated Shelter" if lang == "en" else "नामित आश्रय" if lang == "hi" else "நிவாரண முகாம்")

    if lang == "hi":
        if risk == "CRITICAL":
            return f"🚨 फ़्लैशगार्ड: {village} में {hazard_str} का गंभीर खतरा! तुरंत सुरक्षित ऊंचे स्थान/{sh} पर जाएं। बहते पानी में न जाएं। फोन: 1077/112."
        elif risk == "HIGH":
            return f"⚠️ फ़्लैशगार्ड: {village} में {hazard_str} चेतावनी ({window})। निकासी की तैयारी रखें। {sh} पर जाएं। सहायता: 1077."
        else:
            return f"⚠️ फ़्लैशगार्ड: {village} में {hazard_str} जोखिम बढ़ा है। सतर्क रहें, निचले इलाकों से बचें। EOC: 1077."
    elif lang == "ta":
        if risk == "CRITICAL":
            return f"🚨 ஃபிளாஷ்கார்ட்: {village} - {hazard_str} தீவிர அபாயம்! உடனடியாக மேடான இடம்/{sh}க்கு செல்லவும். வெள்ள நீரில் செல்ல வேண்டாம். உதவி: 112."
        elif risk == "HIGH":
            return f"⚠️ ஃபிளாஷ்கார்ட்: {village} - {hazard_str} எச்சரிக்கை ({window}). வெளியேற தயாராகுங்கள். முகாம்: {sh}. உதவி: 112."
        else:
            return f"⚠️ ஃபிளாஷ்கார்ட்: {village} - {hazard_str} அபாய அறிவிப்பு. விழிப்புடன் இருக்கவும், தாழ்வான பகுதிகளை தவிர்க்கவும்."
    else:
        if risk == "CRITICAL":
            return f"🚨 FLASHGUARD: CRITICAL {hazard_str} at {village}! Evacuate immediately to {sh} or safe high ground. DO NOT enter floodwater. Call 112."
        elif risk == "HIGH":
            return f"⚠️ FLASHGUARD: HIGH {hazard_str} WARNING for {village} ({window}). Prepare to evacuate. Shelter: {sh}. Avoid low-lying areas."
        else:
            return f"⚠️ FLASHGUARD: MODERATE {hazard_str} Notice for {village}. Monitor official updates. Avoid flowing water."
